name: "test webhook trigger"                # CHANGE <product_name>
#----------  TRIGGERS  ------------------------------------
on:
  push:
    branches: [ main,release ]
  workflow_dispatch:
  repository_dispatch:
    types: hot-deploy
    
jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------
    - name: Checkout
      uses: actions/checkout@v3
