name: "test webhook trigger"                # CHANGE <product_name>
#----------  TRIGGERS  ------------------------------------
on:
  push:
    branches: [ main,release ]
  workflow_dispatch:
    inputs:
      synopsys_project_id: 
        required: true 
        type: string        
      artifact_path: 
        required: true 
        type: string
        
jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------
    - name: Checkout
      uses: actions/checkout@v3
    #----------------------------------------
    - name: print inputs
      shell: bash
      run: |
        echo "project_id: ${{ github.event.inputs.synopsys_project_id}}"
        echo "artifact_path: ${{ github.event.inputs.artifact_path}}"
        
